---

- name: Ensure nmstate is present
  ansible.builtin.package:
    name: nmstate
  become: true
  when:
    - ansible_facts['os_family'] == "RedHat"
    - _skip_package_install is not defined or
      not (_skip_package_install)

- name: Delete old install dir {{ install_dir }}
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: absent
  when:
    - _delete_install_dir is defined
    - _delete_install_dir

- name: Create install_dir
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    mode: '0755'