---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: {{ ((.Values.aap).name) | default "aap" }}
  namespace: student-services
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  database:
    postgres_storage_class: {{ ((.Values.aap).databaseStorageClass) | default "gp3-csi" }}
  image_pull_policy: IfNotPresent
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: true
    storage_type: file
    file_storage_storage_class: {{ ((.Values.aap).hubFileStorageClass) | default "gp3-csi" }}
    file_storage_size: {{ ((.Values.aap).hubFileStorageSize) | default "10Gi" }}
    redis_storage_class: {{ ((.Values.aap).redisStorageClass) | default "gp3-csi" }}
  lightspeed:
    disabled: true