---
apiVersion: v1
kind: Secret
metadata:
  name: controller-admin-password-hack
  namespace: student-services
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  password: '{{ .Values.controller.adminPassword }}'