{{- range .Values.declarativeStateManagementNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-namespace-admin-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ . }}-argocd-argocd-application-controller
    namespace: {{ . }}
  - kind: ServiceAccount
    name: {{ . }}-argocd-argocd-server
    namespace: {{ . }}
roleRef:
  kind: Role
  name: argocd-namespace-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}