{{- range .Values.declarativeStateManagement }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-namespace-admin-binding
  namespace: {{ .namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .name }}-argocd-argocd-application-controller
    namespace: {{ .namespace }}
  - kind: ServiceAccount
    name: {{ .name }}-argocd-argocd-server
    namespace: {{ .namespace }}
roleRef:
  kind: Role
  name: argocd-namespace-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}