{{- range .Values.declarativeStateManagementNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-edit-on-{{ .}}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}-argocd-argocd-server
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}-argocd-argocd-application-controller
{{- end }}


