{{- range .Values.exampleVirtualMachines }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-datasource-{{ .data_source }}
spec:
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: datasource-checker
      containers:
      - name: wait-for-datasource-{{ .data_source }}
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            oc get datasource {{ .data_source }} -n openshift-virtualization-os-images && break
            echo "Waiting for datasource '{{ .data_source }}'..."
            sleep 5
          done
  backoffLimit: 10
{{- end }}