---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-virtualization-os-images
  name: datasource-access-binding
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: datasource-checker
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: datasource-access-role
  apiGroup: rbac.authorization.k8s.io