---
kind: Node
apiVersion: v1
metadata:
  name: {{ . }}
  labels:
    cluster.ocs.openshift.io/openshift-storage: ''
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false