---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: label-nodes-role
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
