apiVersion: v1
kind: ConfigMap
metadata:
  name: 'codesys-user-settings'
  namespace: default
data: 
  user-config: |
      ;virtuallinux
      [CmpLog]
      Logger.0.Filter=0x0000000F

      [ComponentManager]
      Component.1=CmpBACnet
      Component.2=CmpBACnet2
      Component.3=CmpPLCHandler
      Component.4=CmpGwClient
      Component.5=CmpXMLParser
      Component.6=CmpGwClientCommDrvTcp
      ;Component.7=CmpGwClientCommDrvShm ; enable only if necessary, can result in higher cpu load
      ;Component.8=SysPci				; enable when using Hilscher CIFX
      ;Component.9=CmpHilscherCIFX	; enable when using Hilscher CIFX

      [CmpApp]
      Bootproject.RetainMismatch.Init=1
      ;RetainType.Applications=InSRAM
      Application.1=Application

      [CmpRedundancyConnectionIP]

      [CmpRedundancy]

      [CmpSrv]

      [IoDrvEtherCAT]

      [SysTarget]
      SerialNumber=RTS-00000000333a536a

      [CmpSecureChannel]
      SECURITY.CommunicationMode=ONLY_PLAIN

      [CmpUserMgr]
      AsymmetricAuthKey=0a41d6cf5363d976dce29a300697919b8ece69bd
      SECUTITY.UserMgmtEnforce=NO
      SECURITY.UserMgmtAllowAnonymous=YES

      [CmpSecureChannel]
      CertificateHash=3c0f5865dd0f0fa209668e8f68c2d1341f37a805
immutable: false
