---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: students-htpasswd-auth
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: students-htpass