---

collections:
  - name: ansible.utils
    version: '*'
  - name: ansible.posix
  - name: awx.awx
  - name: community.aws
  - name: community.crypto
  - name: community.general
  - name: community.mysql
  - name: community.libvirt
  - name: community.kubernetes
  - name: containers.podman
  - name: redhat_cop.controller_configuration
  - name: fedora.linux_system_roles
  #- name: redhat.openshift
  - name: https://github.com/ansible-collections/community.fdo.git
    type: git
  - name: kubernetes.core
  #- name: https://github.com/jjaswanson4/kubernetes.core.git
  #  type: git
  - name: https://github.com/jjaswanson4/infra.osbuild.git
    type: git
