{{- with .Values.zeroSSL }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zero-ssl-eabsecret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  secret: {{ .key }}
{{- end }}
{{- with .Values.cloudflare }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  api-token: {{ .token }}
{{- end }}
{{- with .Values.route53 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-secret-access-key
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  aws_secret_access_key: {{ .aws_secret_access_key }}
{{- end }}
