---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configure-controller
  namespace: openshift-gitops
  labels:
    application: configure-controller
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: student-services
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/redhat-manufacturing/device-edge-workshops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/configure-controller/
    helm:
      values: |
        controller:
{{ toYaml .Values.controller | nindent 10 }}