---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
  labels:
    application: gitea
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/redhat-manufacturing/device-edge-workshops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/gitea/
    helm:
      values: |
        gitea:
{{ toYaml .Values.gitea | nindent 10 }}