---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-operator
  namespace: openshift-gitops
  labels:
    application: gitea-operator
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/rhpds/gitea-operator.git
    targetRevision: HEAD
