---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-infrastructure
  namespace: openshift-gitops
  labels:
    application: network-infrastructure
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/redhat-manufacturing/device-edge-workshops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/network-infrastructure/
    helm:
      values: |
        networkInfrastructure:
{{ toYaml .Values.networkInfrastructure | nindent 10 }}