---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-users
  namespace: openshift-gitops
  labels:
    application: student-users
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: student-services
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/redhat-manufacturing/device-edge-workshops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/student-users/
    helm:
      values: |
        studentUsers:
{{ toYaml .Values.studentUsers | nindent 10 }}