apiVersion: build.openshift.io/v1
kind: Build
metadata:
  name: student-pages-10
  labels:
    app.kubernetes.io/instance: student-pages
    buildconfig: student-pages
    openshift.io/build-config.name: student-pages
    openshift.io/build.start-policy: Serial
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccount: builder
  triggeredBy:
    - message: "Manually triggered"
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-manufacturing/device-edge-workshops.git'
      ref: {{ .Values.gitBranch | default "main" }}
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: STUDENT_TOTAL
          value: '{{ .Values.studentTotal }}'
        - name: ADMIN_PASSWORD
          value: '{{ .Values.adminPassword }}'
        - name: BASE_ZONE
          value: '{{ .Values.baseZone }}'
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'student-pages:latest'
