---
---
apiVersion: batch/v1
kind: Job
metadata:
  name: start-student-pages-build
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
        - name: start-student-pages-build
          image: openshift4/ose-cli:latest
          command:
            - /usr/bin/oc start-build student-pages
      restartPolicy: OnFailure

