---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger-build-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-full-access
subjects:
- kind: ServiceAccount
  name: trigger-build
  namespace: {{ .Release.Namespace }}