---
apiVersion: v1
kind: Service
metadata:
  name: student-pages-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: student-pages
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort