---

- name: Create teams in gitea
  hosts:
    - localhost
  gather_facts: false
  connection: local
  pre_tasks:
    - name: Import variables from /runner/variables
      ansible.builtin.include_vars:
        dir: /runner/variables
  tasks:
    - name: Create teams
      ansible.builtin.uri:
        url: "{{ gitea.url }}/api/v1/orgs/{{ team.organization }}/teams"
        validate_certs: false
        user: "{{ gitea.admin.username | default('instructor') }}"
        password: '{{ gitea.admin.password }}'
        force_basic_auth: true
        body_format: json
        method: POST
        body:
          can_create_org_repo: "{{ true | bool }}"
          name: "{{ team.name }}"
          permission: write
          includes_all_repositories: "{{ false | bool }}"
          units:
            - repo.code
            - repo.issues
            - repo.ext_issues
            - repo.wiki
            - repo.pulls
            - repo.releases
            - repo.projects
            - repo.ext_wiki
        status_code:
          - 201
          - 422
      loop: "{{ gitea.teams }}"
      loop_control:
        loop_var: team
      when:
        - gitea.teams is defined