---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
  labels:
    application: acp-standard-services
spec:
  destination:
    name: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/RedHatEdge/acp-standard-services.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/cert-manager/
    helm: |
      baseZone: {{ .Values.baseZone }}
      clusterName: {{ .Values.clusterName }}
      zeroSSL:
{{- with .Values.zeroSSL }}
        email: {{ .email }}
        keyID: {{ .keyID }}
        key: {{ .key }}
{{- end }}
{{- with .Values.cloudflare }}
      cloudflare:
        email: {{ .email }}
        token: {{ .token }}
{{- end }}