---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-automation
  namespace: openshift-gitops
  labels:
    application: it-automation
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/redhat-manufacturing/device-edge-workshops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: provisioner/charts/it-automation/
    syncPolicy:
      automated: {}
    helm:
