---

- name: build and start local services
  hosts:
    - edge-manager-local
  pre_tasks:
    - name: attempt to load in vars for workshop
      ansible.builtin.include_vars:
        file: "workshop_vars/{{ workshop_type }}.yml"
  tasks:
    - name: build local services
      ansible.builtin.include_role:
        name: ../roles/build_local_services
      # loop: "{{ local_services }}"
      # loop_control:
      #   loop_var: service
