---

- name: Install an OCP cluster on AWS
  hosts:
    - edge_management
  roles:
    - ../roles/install_ocp_on_aws
  post_tasks:
    - name: Post-install tasks
      when:
        - teardown is not defined or
          not teardown|bool
      block:
        - name: Install pip
          ansible.builtin.package:
            name: python3-pip
          become: true
          tags:
            - always
        - name: Install kubernetes python library
          ansible.builtin.pip:
            name: kubernetes
          tags:
            - always
        - name: Create /home/{{ ansible_user }}/.kube dir
          ansible.builtin.file:
            path: /home/{{ ansible_user }}/.kube
            state: directory
            owner: "{{ ansible_user }}"
        - name: Link kubeconfig to default location
          ansible.builtin.file:
            src: "{{ install_dir }}/install/auth/kubeconfig"
            dest: "/home/{{ ansible_user }}/.kube/config"
            state: link
          tags:
            - always
            - link_kubeconfig
