---

- name: reset local services completely
  hosts:
    - 'edge_management:&local'
    - edge_local_management
  pre_tasks:
    - name: attempt to load in vars for workshop
      ansible.builtin.include_vars:
        file: "workshop_vars/{{ workshop_type }}.yml"
  tasks:
    - name: loop over pods
      ansible.builtin.include_role:
        name: ../roles/run_local_services
        apply:
          become: "{{ pod.privileged | default(false) }}"
          vars:
            state: absent
      loop: "{{ pods }}"
      loop_control:
        loop_var: pod
    - name: dump the images
      containers.podman.podman_image:
        name: "localhost/{{ image.name }}:latest"
        state: absent
      loop: "{{ local_services }}"
      loop_control:
        loop_var: image
    - name: dump the volumes
      containers.podman.podman_volume:
        name: workshop-rhde_tse-database
        state: absent
    - name: dump the code repo dirs
      ansible.builtin.file:
        path: "/tmp/{{ ansible_host }}"
        state: absent
    - name: become tasks
      become: true
      block:
        - name: dump dnsmasq | priv
          containers.podman.podman_image:
            name: localhost/dnsmasq:latest
            state: absent
        - name: umount boot iso
          ansible.posix.mount:
            path: "/home/{{ ansible_user }}/workshop-build/ipxe/boot_iso"
            state: unmounted
        - name: remove the build directory
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/workshop-build"
            state: absent
        - name: dump the nm connection
          community.general.nmcli:
            conn_name: "{{ workshop_type }}-workshop"
            state: absent
        - name: remove fdo
          ansible.builtin.dnf:
            name: fdo-admin-cli
            state: absent
        - name: wipe fdo config
          ansible.builtin.file:
            path: /etc/fdo
            state: absent
