---

- name: start local services up
  hosts:
    - 'edge_management:&local'
    - edge_local_management
  pre_tasks:
    - name: attempt to load in vars for workshop
      ansible.builtin.include_vars:
        file: "{{ workshop_or_demo | default('workshop') }}_vars/{{ workshop_type }}.yml"
  tasks:
    - name: loop over pods
      ansible.builtin.include_role:
        name: ../roles/run_local_services
        apply:
          become: "{{ pod.privileged | default(false) }}"
      loop: "{{ pods }}"
      loop_control:
        loop_var: pod
