{{- range .Values.virtualMachineImports }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: {{ .name }}
  namespace: openshift-virtualization-os-images
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  source:
    pvc:
      name: {{ .name }}
      namespace: openshift-virtualization-os-images
{{- end }}
