---
- name: Setup OSPF
  hosts:
    - all
  tasks:
    - name: Configure OSPFv2
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              max_metric:
                router_lsa: true
                on_startup:
                  time: 110
              areas:
                - area_id: "0"
                  capability: true