---
- name: Setup SNMPv2
  hosts:
    - all
  tasks:
    - name: Configure SNMPv2 read-only
      cisco.ios.ios_snmp_server:
        config:
          communities:
            - name: ansible
              ro: true