---
- name: Setup static routes
  hosts:
    - all
  tasks:
    - name: Configure static routes
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 10.1.1.0/24
                    next_hops:
                      - forward_router_address: 192.168.1.1
                        name: route
                  - dest: 10.1.2.0/24
                    next_hops:
                      - forward_router_address: 192.168.2.1
                        name: route2
                  - dest: 10.1.3.0/24
                    next_hops:                       
                      - forward_router_address: 192.168.3.1
                        name: route3
